### ISSUE TITLE
Not working with "Sanskrit"

### ISSUE THREAD

**Issue by chinchang** [eemeli/make-plural#12]
Hi, I am trying to get this work with the language "Sanskrit". But seems like it's not supported as I can't find it listed here -> http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

Can someone please give me direction on adding support for "Sanskrit" in this module?

Thanks

**Comment by longlho** [comment]
you should submit a ticket upstream in Unicode CLDR itself 😄

**Comment by longlho** [comment]
@chinchang I think that falls under `sa` locale actually

**Comment by eemeli** [comment]
Closing as this is effectively answered by @longlho above. Apologies on my part on having missed this.
