### ISSUE TITLE
v6.1.2 breaks expectations of v6.1.0

### ISSUE THREAD

**Issue by aredridel** [eemeli/make-plural#16]
By introducing exports in package.json that do not export package.json itself, intl-pluraltools can no longer require package.json on current node versions.

**Comment by eemeli** [comment]
Could you specify what package.json info you were trying to use? Also, is "intl-pluraltools" a publicly available package? I wasn't able to find any references to it.

**Comment by aredridel** [comment]
Agh, my apologies: intl-pluralrules. Which I now realize is also your work. It's been a long day. 

Actually looking deeper, it looks like I misread the error, and it was the requiring of intl-pluralrules' package.json, and the error is in that requiring code — it blindly tries package.json in all modules it loads, which is more a breakage caused by node than anything you're involved in. My apologies for the noise.

**Comment by aredridel** [comment]
That said, it sure appears that adding exports is semver-major unless they're exceptionally thorough.
