### ISSUE TITLE
Chinese plurals function only return 'other'

### ISSUE THREAD

**Issue by Akarinx** [eemeli/make-plural#27]
Hi @eemeli !
Thanks for providing this open source repository.
```Typescript 
// make-plural/plurals.js

const a = (n, ord) => {
  if (ord) return 'other';
  return n == 1 ? 'one' : 'other';
};

const e = (n, ord) => 'other';

(function (root, plurals) {
  Object.defineProperty(plurals, '__esModule', { value: true });
  if (typeof define === 'function' && define.amd) define(plurals);
  else if (typeof exports === 'object') module.exports = plurals;
  else root.plurals = plurals;
}(this, {
// ...
  zh: e  // only return 'other'

}
```

Maybe Chinese plurals function can return 'one' | 'other' like English ?
In some cases, the text for singular and plural is different, but now I need to use more than one text to resolve these cases.

Looking forward to your reply!

**Comment by eemeli** [comment]
This library relies on CLDR data for plurals, which only provides an `other` category for Chinese: https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#zh

If you're looking to provide a different message variant when your selector value is exactly 1, you should test for that separately, as the CLDR `one` category often has a slightly different meaning.

**Comment by Akarinx** [comment]
I got it.
And I found the same question [https://chinese.stackexchange.com/questions/34968/is-it-more-natural-to-express-0-with-a-negative-form](url), but the question is gone without answer.
By CLDR, it is unlikely to modify the source code to solve the problem, and I need to use more than one text to resolve these cases.😣

Thank you for your reply !!
